### ISSUE TITLE
How to work with falsefolder parameter?

### ISSUE THREAD

**Issue by InbarKedem** [slanj/yolo-tiling#1]
Hey, 
I want to get all the images without bounding box. As I understood, I should use the falsefolder parameter. 
When I use it, with empty folder, it raise me this problem. 
```
Traceback (most recent call last):
  File "tile_yolo.py", line 152, in <module>
    raise Exception("Target folder should be empty")
Exception: Target folder should be empty
```

Maybe I misunderstood the way I of using it, @slanj can you please provide an example of usage?

**Comment by slanj** [comment]
In any case you should provide empty target folder in addition to falsefolder. Script will not process images without it. Provide an example, how you call the script and parameters used.

**Comment by InbarKedem** [comment]
Finally, I was able to use the tiling after a lot of struggling. 
This script is specific to work under some cases, without the validation of edge cases (for example, a target folder is not empty, or images and labels number is not the same). 
If you want to make it more universal, you can add these features. 

In case someone will use it, I'll add the usage that works for me:
`python3 tile_yolo.py -source ./images/ -target ./yolosliced/ts/ -ext .png -size 416 -falsefolder ./yolosliced/ts/false/`
