### ISSUE TITLE
Annotations become messed up after tiling

### ISSUE THREAD

**Issue by chuachengling** [slanj/yolo-tiling#3]
Hey there, thanks for the script! unfortunately, the annotations becomes abit messed up after tiling, any suggestions to resolve that? Thanks!

**Comment by slanj** [comment]
Hello. What do you mean in "messed"? If tiling is incorrect - re-check your annotation. Coordinates should be in 0-1 range.

**Comment by chuachengling** [comment]
Hello, when I mean messed, the tiling becomes incorrect. The coordinates are ranged from 0-1 currently.

I am splitting the image into a resolution of 1280 x 1280,  but after doing so, the annotations go all over the place,.

![Screen Shot 2021-10-06 at 11 49 18 PM](https://user-images.githubusercontent.com/45548701/136238700-016f7931-7749-4ef1-b03d-3d35cfecdd9a.png)

**Comment by slanj** [comment]
Provide more detailed information about your problem. Show sample annotation, sample image, script parameters you used  and expected behavior.
For now I just see some bounding boxes on a grey background.

**Comment by chuachengling** [comment]
Hello, apologies, unfortunately, I cannot show more of the image and annotations because of the sensitive nature of the data. Let me try my best to describe the problem:

The image I want to tile is 4032 × 2268 in size.

Annotations are:

3 0.175719 0.591490 0.006200 0.008377
2 0.186012 0.649471 0.008929 0.008818
2 0.230407 0.728395 0.005456 0.015873
2 0.205233 0.695547 0.008185 0.006614
[Truncated, around 200 more labels]

Parameters used were:
python tile_yolo.py -source test_split -target test_folder -ext .jpg -size 1280

The expected output is images 1280 x 1280 minimally, with the excess tiled as well.

Thank you so much!

**Comment by slanj** [comment]
Annotation looks ok. So, you get correct slices and incorrect annotation for each slice? 
You have big slice size of 1280 x 1280 . With this size you will get only thee slices from  4032 × 2268 image. (4032  // 1280 = 3) . 
This script does not expand image if a slice does not fit.

**Comment by chuachengling** [comment]
Yep, I get correct slices but incorrect annotations

**Comment by slanj** [comment]
I have created sample image based on your size and annotation. Splitting works fine. Except it will not include tiles that do not fit on on excess.

**Comment by chuachengling** [comment]
I have resolved the issue, thanks!

**Comment by isspid** [comment]
> 
> 
> I have resolved the issue, thanks!

@chuachengling 
Could you please explain how you solved the issue?

**Comment by chuachengling** [comment]
@isspid 

The script mainly focuses on tiling the images into your desired slice_size, however, it does not allow you to cut it into rectangles of other sizes. I modified the script by cutting it up into N and M slices closest to the desired slice_size

```
dim_h = math.ceil(height/slice_size) 
dim_w = math.ceil(width/slice_size) 
slice_size_h = int(height/dim_h)
slice_size_w = int(width/dim_w)
```

I then modified the labels manually (without using the shapely package given with some math for the new tiled images and saved it to a dataframe only if they are considered valid labels (0 to 1)

```
for k in range(len(labels)):
                new_x = (labels.iloc[k,:]['x1'] - j * slice_size_w) / slice_size_w
                new_y = (labels.iloc[k,:]['y1'] - i * slice_size_h) / slice_size_h
                new_width = (labels.iloc[k,:]['w'] )/slice_size_w
                new_height = (labels.iloc[k,:]['h'] )/slice_size_h

                if 0 <= new_x <= 1 and 0<=new_y<=1:
                    slice_labels.append([int(labels.iloc[k,:]['class']),new_x,new_y,new_width,new_height])
```

Then the rest of the script kinda follows.
