### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by isspid** [slanj/yolo-tiling#4]
When I run the script I get this error:

`C:\Users\istaka\tiling\yolo-tiling>python tile_yolo.py -source C:\Users\istaka\tiling\prova\obj_train_data -target C:\Users\istaka\tiling\prova\shenja\fotot -ext .jpeg -size 512

Image: C:\Users\istaka\tiling\prova\obj_train_data\1_Mundsburger Damm_41_ANSN__.jpeg

C:\Users\istaka\tiling\prova\shenja\fotot/C:\Users\istaka\tiling\prova\obj_train_data\1_Mundsburger Damm_41_ANSN___0_1.jpeg

Traceback (most recent call last):
  File "C:\Users\istaka\tiling\yolo-tiling\tile_yolo.py", line 169, in <module>
    tiler(imnames, args.target, args.falsefolder, args.size, args.ext)
  File "C:\Users\istaka\tiling\yolo-tiling\tile_yolo.py", line 61, in tiler
    sliced_im.save(slice_path)
  File "C:\Users\istaka\Anaconda3\envs\data_size\lib\site-packages\PIL\Image.py", line 2232, in save
    fp = builtins.open(filename, "w+b")

OSError: [Errno 22] Invalid argument: 'C:\\Users\\istaka\\tiling\\prova\\shenja\\fotot/C:\\Users\\istaka\\tiling\\prova\\obj_train_data\\1_Mundsburger Damm_41_ANSN___0_1.jpeg'`

 I am using windows and I suspect the error has to do with the way paths are being processed but I couldn't manage to fix it. Have you got any ideas?

**Comment by slanj** [comment]
I have not tested it on Windows. One suggestion - do not use absolute paths. Place script and images folder in one directory. And use relative paths to that directory.

**Comment by isspid** [comment]
> 
> 
> I have not tested it on Windows. One suggestion - do not use absolute paths. Place script and images folder in one directory. And use relative paths to that directory.

Your suggestion worked. Thank you very much for the fast reply.
